import type { CorrectionEntry } from "../types";

export const MOCK_CORRECTIONS: CorrectionEntry[] = [
  {
    id: "corr-001",
    timestamp: "2026-03-14T10:45:00Z",
    action: "mapping_change",
    description: "Mapped 'PatientNr' → 'patient_id' in patient_registry",
    sourceFileId: "src-001",
    field: "PatientNr",
    previousValue: "unmapped",
    newValue: "patient_id",
    appliedBy: "ai",
  },
  {
    id: "corr-002",
    timestamp: "2026-03-14T10:48:00Z",
    action: "value_fix",
    description: "Standardised date format in 'Entlassdatum' from DD.MM.YYYY to ISO 8601",
    sourceFileId: "src-001",
    field: "Entlassdatum",
    previousValue: "DD.MM.YYYY (17%)",
    newValue: "YYYY-MM-DD (100%)",
    appliedBy: "ai",
  },
  {
    id: "corr-003",
    timestamp: "2026-03-14T11:02:00Z",
    action: "mapping_change",
    description: "Mapped 'Laborwert' → 'lab_test_name' in lab_results",
    sourceFileId: "src-002",
    field: "Laborwert",
    previousValue: "unmapped",
    newValue: "lab_test_name",
    appliedBy: "ai",
  },
  {
    id: "corr-004",
    timestamp: "2026-03-14T11:15:00Z",
    action: "field_rename",
    description: "Renamed target field 'pat_id' → 'patient_id' for consistency",
    field: "pat_id",
    previousValue: "pat_id",
    newValue: "patient_id",
    appliedBy: "user",
  },
  {
    id: "corr-005",
    timestamp: "2026-03-14T11:20:00Z",
    action: "schema_update",
    description: "Added 'Bemerkung' column to unmapped fields queue after schema drift detection",
    sourceFileId: "src-001",
    field: "Bemerkung",
    appliedBy: "ai",
  },
  {
    id: "corr-006",
    timestamp: "2026-03-14T11:30:00Z",
    action: "value_fix",
    description: "Flagged 3 lab results with out-of-range CRP values for review",
    sourceFileId: "src-002",
    field: "Ergebnis",
    previousValue: "48.5, 85.3 mg/L",
    newValue: "flagged for review",
    appliedBy: "ai",
  },
];
