import type { FieldMapping } from "../types";

export const MOCK_MAPPINGS: FieldMapping[] = [
  // ── care_assessments.csv → care_assessments table ──
  {
    id: "map-001",
    sourceFileId: "src-001",
    sourceColumn: "Sturzrisiko_Skala",
    sampleValue: "3",
    targetTable: "care_assessments",
    targetColumn: "score",
    confidence: 0.92,
    reasoning: "Column name translates to 'Fall Risk Scale', values 0–4 match score range.",
    status: "accepted",
    transformation: "CAST(value AS INTEGER)",
  },
  {
    id: "map-002",
    sourceFileId: "src-001",
    sourceColumn: "Mobilität",
    sampleValue: "2",
    targetTable: "care_assessments",
    targetColumn: "score",
    confidence: 0.87,
    reasoning: "German for 'Mobility'. Values 0–4 consistent with standardised mobility assessment scale.",
    status: "accepted",
    transformation: "CAST(value AS INTEGER)",
  },
  {
    id: "map-003",
    sourceFileId: "src-001",
    sourceColumn: "Ernährung",
    sampleValue: "2",
    targetTable: "care_assessments",
    targetColumn: "score",
    confidence: 0.85,
    reasoning: "Translates to 'Nutrition'. Numeric values indicate a standardised nutrition screening score.",
    status: "accepted",
    transformation: "CAST(value AS INTEGER)",
  },
  {
    id: "map-004",
    sourceFileId: "src-001",
    sourceColumn: "Schmerz",
    sampleValue: "4",
    targetTable: "care_assessments",
    targetColumn: "score",
    confidence: 0.89,
    reasoning: "Translates to 'Pain'. Values 0–10 align with Visual Analog Scale (VAS) pain scoring.",
    status: "accepted",
    transformation: "CAST(value AS INTEGER)",
  },
  {
    id: "map-005",
    sourceFileId: "src-001",
    sourceColumn: "Dekubitus",
    sampleValue: "0",
    targetTable: "care_assessments",
    targetColumn: "score",
    confidence: 0.91,
    reasoning: "Translates to 'Pressure Ulcer'. Values 0–4 match Braden/Norton sub-scale range.",
    status: "accepted",
    transformation: "CAST(value AS INTEGER)",
  },
  {
    id: "map-006",
    sourceFileId: "src-001",
    sourceColumn: "PatientNr",
    sampleValue: "P-10042",
    targetTable: "care_assessments",
    targetColumn: "patient_id",
    confidence: 0.95,
    reasoning: "Standard patient number field. Format P-XXXXX matches patient registry pattern.",
    status: "accepted",
  },
  {
    id: "map-007",
    sourceFileId: "src-001",
    sourceColumn: "Station",
    sampleValue: "A1",
    targetTable: "care_assessments",
    targetColumn: "ward",
    confidence: 0.78,
    reasoning: "German for 'Ward/Station'. Low cardinality with values A1, A2, B1, B2, C1 matching known wards.",
    status: "accepted",
  },
  {
    id: "map-008",
    sourceFileId: "src-001",
    sourceColumn: "Datum",
    sampleValue: "2026-03-10",
    targetTable: "care_assessments",
    targetColumn: "assessed_at",
    confidence: 0.9,
    reasoning: "Translates to 'Date'. ISO 8601 format dates correspond to assessment timestamps.",
    status: "accepted",
    transformation: "CAST(value AS TIMESTAMP)",
  },
  {
    id: "map-009",
    sourceFileId: "src-001",
    sourceColumn: "Beurteiler",
    sampleValue: "Müller, K.",
    targetTable: "care_assessments",
    targetColumn: "assessor_name",
    confidence: 0.83,
    reasoning: "Translates to 'Assessor'. Contains staff surname-initial patterns.",
    status: "accepted",
  },
  {
    id: "map-010",
    sourceFileId: "src-001",
    sourceColumn: "Aufnahmedatum",
    sampleValue: "2026-03-01",
    targetTable: "encounters",
    targetColumn: "admitted_at",
    confidence: 0.88,
    reasoning: "Translates to 'Admission Date'. Links assessment to the patient encounter.",
    status: "accepted",
    transformation: "CAST(value AS TIMESTAMP)",
  },
  {
    id: "map-011",
    sourceFileId: "src-001",
    sourceColumn: "Entlassdatum",
    sampleValue: "2026-03-15",
    targetTable: "encounters",
    targetColumn: "discharged_at",
    confidence: 0.72,
    reasoning: "Translates to 'Discharge Date'. Contains nulls for current inpatients and mixed date formats (ISO 8601 vs DD.MM.YYYY). Needs standardisation before mapping.",
    status: "pending",
    transformation: "COALESCE(CAST(value AS TIMESTAMP), NULL)",
  },
  {
    id: "map-012",
    sourceFileId: "src-001",
    sourceColumn: "Bemerkung",
    sampleValue: "Sturzgefahr erhöht",
    targetTable: "care_assessments",
    targetColumn: "notes",
    confidence: 0.34,
    reasoning: "Translates to 'Notes'. Free-text field with 61% null rate; semantic purpose unclear. Could be clinical notes or administrative comments — needs manual review.",
    status: "rejected",
  },

  // ── lab_results.xlsx → lab_results table ──
  {
    id: "map-013",
    sourceFileId: "src-002",
    sourceColumn: "PatientNr",
    sampleValue: "P-10042",
    targetTable: "lab_results",
    targetColumn: "patient_id",
    confidence: 0.95,
    reasoning: "Patient number format identical to care_assessments source, enabling cross-file joins.",
    status: "accepted",
  },
  {
    id: "map-014",
    sourceFileId: "src-002",
    sourceColumn: "Laborwert",
    sampleValue: "Hämoglobin",
    targetTable: "lab_results",
    targetColumn: "test_name",
    confidence: 0.88,
    reasoning: "Translates to 'Lab Value'. Contains standardised German test names (Hämoglobin, Kreatinin, CRP, Leukozyten).",
    status: "accepted",
  },
  {
    id: "map-015",
    sourceFileId: "src-002",
    sourceColumn: "Ergebnis",
    sampleValue: "13.2",
    targetTable: "lab_results",
    targetColumn: "value",
    confidence: 0.91,
    reasoning: "Translates to 'Result'. Numeric values consistent with expected lab measurement ranges.",
    status: "accepted",
    transformation: "CAST(value AS DECIMAL(10,2))",
  },
  {
    id: "map-016",
    sourceFileId: "src-002",
    sourceColumn: "Einheit",
    sampleValue: "g/dL",
    targetTable: "lab_results",
    targetColumn: "unit",
    confidence: 0.93,
    reasoning: "Translates to 'Unit'. Contains standard measurement units (g/dL, mg/L, ×10³/µL).",
    status: "accepted",
  },
  {
    id: "map-017",
    sourceFileId: "src-002",
    sourceColumn: "Referenzbereich",
    sampleValue: "12.0–16.0",
    targetTable: "lab_results",
    targetColumn: "reference_range",
    confidence: 0.85,
    reasoning: "Translates to 'Reference Range'. Dash-separated min–max values matching clinical standards.",
    status: "accepted",
  },
  {
    id: "map-018",
    sourceFileId: "src-002",
    sourceColumn: "Messzeitpunkt",
    sampleValue: "2026-03-10T08:15",
    targetTable: "lab_results",
    targetColumn: "measured_at",
    confidence: 0.9,
    reasoning: "Translates to 'Measurement Time'. ISO 8601 timestamps with timezone.",
    status: "accepted",
    transformation: "CAST(value AS TIMESTAMP WITH TIME ZONE)",
  },
  {
    id: "map-019",
    sourceFileId: "src-002",
    sourceColumn: "Laborcode",
    sampleValue: "HGB",
    targetTable: "lab_results",
    targetColumn: "test_code",
    confidence: 0.65,
    reasoning: "Short alphanumeric codes (HGB, CREA, CRP, WBC). May map to LOINC but codes are non-standard abbreviations. Needs validation against a terminology service.",
    status: "pending",
  },
  {
    id: "map-020",
    sourceFileId: "src-002",
    sourceColumn: "Station",
    sampleValue: "A1",
    targetTable: "lab_results",
    targetColumn: "ward",
    confidence: 0.76,
    reasoning: "Ward identifier matching care_assessments Station field. Could alternatively link via encounters table rather than denormalising.",
    status: "pending",
  },
];
