import type { ColumnProfile } from "../types";

export const MOCK_PROFILES: Record<string, ColumnProfile[]> = {
  "src-001": [
    {
      id: "col-001",
      sourceFileId: "src-001",
      columnName: "Sturzrisiko_Skala",
      inferredType: "number",
      semanticLabel: "Fall Risk Score",
      domain: "care_assessments",
      confidence: 0.92,
      sampleValues: [2, 1, 3, 0, 4, 2, 1],
      qualityFlags: [],
      userCorrected: false,
    },
    {
      id: "col-002",
      sourceFileId: "src-001",
      columnName: "Mobilität",
      inferredType: "number",
      semanticLabel: "Mobility Score",
      domain: "care_assessments",
      confidence: 0.87,
      sampleValues: [3, 2, 1, 4, 2, 3, 1],
      qualityFlags: [],
      userCorrected: false,
    },
    {
      id: "col-003",
      sourceFileId: "src-001",
      columnName: "Ernährung",
      inferredType: "number",
      semanticLabel: "Nutrition Score",
      domain: "care_assessments",
      confidence: 0.85,
      sampleValues: [2, 3, 1, 2, 4, 3, 2],
      qualityFlags: [],
      userCorrected: false,
    },
    {
      id: "col-004",
      sourceFileId: "src-001",
      columnName: "Schmerz",
      inferredType: "number",
      semanticLabel: "Pain Score",
      domain: "care_assessments",
      confidence: 0.89,
      sampleValues: [4, 7, 2, 0, 5, 8, 3],
      qualityFlags: [],
      userCorrected: false,
    },
    {
      id: "col-005",
      sourceFileId: "src-001",
      columnName: "Dekubitus",
      inferredType: "number",
      semanticLabel: "Pressure Ulcer Score",
      domain: "care_assessments",
      confidence: 0.91,
      sampleValues: [0, 1, 2, 0, 3, 1, 0],
      qualityFlags: [],
      userCorrected: false,
    },
    {
      id: "col-006",
      sourceFileId: "src-001",
      columnName: "PatientNr",
      inferredType: "string",
      semanticLabel: "Patient ID",
      domain: "care_assessments",
      confidence: 0.95,
      sampleValues: ["P-10042", "P-10078", "P-10115", "P-10203"],
      qualityFlags: [],
      userCorrected: false,
    },
    {
      id: "col-007",
      sourceFileId: "src-001",
      columnName: "Station",
      inferredType: "string",
      semanticLabel: "Ward",
      domain: "care_assessments",
      confidence: 0.78,
      sampleValues: ["A1", "A2", "B1", "B2", "C1"],
      qualityFlags: ["low_cardinality"],
      userCorrected: false,
    },
    {
      id: "col-008",
      sourceFileId: "src-001",
      columnName: "Datum",
      inferredType: "date",
      semanticLabel: "Assessment Date",
      domain: "care_assessments",
      confidence: 0.9,
      sampleValues: ["2026-03-10", "2026-03-11", "2026-03-12"],
      qualityFlags: [],
      userCorrected: false,
    },
    {
      id: "col-009",
      sourceFileId: "src-001",
      columnName: "Beurteiler",
      inferredType: "string",
      semanticLabel: "Assessor",
      domain: "care_assessments",
      confidence: 0.83,
      sampleValues: ["Müller, K.", "Schmidt, A.", "Weber, L."],
      qualityFlags: [],
      userCorrected: false,
    },
    {
      id: "col-010",
      sourceFileId: "src-001",
      columnName: "Aufnahmedatum",
      inferredType: "date",
      semanticLabel: "Admission Date",
      domain: "care_assessments",
      confidence: 0.88,
      sampleValues: ["2026-03-01", "2026-02-27", "2026-03-05"],
      qualityFlags: [],
      userCorrected: false,
    },
    {
      id: "col-011",
      sourceFileId: "src-001",
      columnName: "Entlassdatum",
      inferredType: "date",
      semanticLabel: "Discharge Date",
      domain: "care_assessments",
      confidence: 0.72,
      sampleValues: ["2026-03-15", "", "2026-03-18"],
      qualityFlags: ["nullable", "mixed_formats"],
      userCorrected: false,
    },
    {
      id: "col-012",
      sourceFileId: "src-001",
      columnName: "Bemerkung",
      inferredType: "string",
      semanticLabel: "Notes",
      domain: "care_assessments",
      confidence: 0.34,
      sampleValues: [
        "Sturzgefahr erhöht",
        "",
        "Mobilisation eingeleitet",
        "",
      ],
      qualityFlags: ["high_null_rate", "unknown_semantics"],
      userCorrected: false,
    },
  ],

  "src-002": [
    {
      id: "col-013",
      sourceFileId: "src-002",
      columnName: "PatientNr",
      inferredType: "string",
      semanticLabel: "Patient ID",
      domain: "lab_results",
      confidence: 0.95,
      sampleValues: ["P-10042", "P-10078", "P-10115", "P-10203"],
      qualityFlags: [],
      userCorrected: false,
    },
    {
      id: "col-014",
      sourceFileId: "src-002",
      columnName: "Laborwert",
      inferredType: "string",
      semanticLabel: "Test Name",
      domain: "lab_results",
      confidence: 0.88,
      sampleValues: ["Hämoglobin", "Kreatinin", "CRP", "Leukozyten"],
      qualityFlags: [],
      userCorrected: false,
    },
    {
      id: "col-015",
      sourceFileId: "src-002",
      columnName: "Ergebnis",
      inferredType: "number",
      semanticLabel: "Value",
      domain: "lab_results",
      confidence: 0.91,
      sampleValues: [13.2, 1.1, 48.5, 7.8],
      qualityFlags: [],
      userCorrected: false,
    },
    {
      id: "col-016",
      sourceFileId: "src-002",
      columnName: "Einheit",
      inferredType: "string",
      semanticLabel: "Unit",
      domain: "lab_results",
      confidence: 0.93,
      sampleValues: ["g/dL", "mg/dL", "mg/L", "×10³/µL"],
      qualityFlags: [],
      userCorrected: false,
    },
    {
      id: "col-017",
      sourceFileId: "src-002",
      columnName: "Referenzbereich",
      inferredType: "string",
      semanticLabel: "Reference Range",
      domain: "lab_results",
      confidence: 0.85,
      sampleValues: ["12.0–16.0", "0.6–1.2", "<5.0", "4.0–10.0"],
      qualityFlags: [],
      userCorrected: false,
    },
    {
      id: "col-018",
      sourceFileId: "src-002",
      columnName: "Messzeitpunkt",
      inferredType: "date",
      semanticLabel: "Measured At",
      domain: "lab_results",
      confidence: 0.9,
      sampleValues: [
        "2026-03-10T08:15:00Z",
        "2026-03-11T07:45:00Z",
        "2026-03-12T09:00:00Z",
      ],
      qualityFlags: [],
      userCorrected: false,
    },
    {
      id: "col-019",
      sourceFileId: "src-002",
      columnName: "Laborcode",
      inferredType: "code",
      semanticLabel: "Test Code",
      domain: "lab_results",
      confidence: 0.82,
      sampleValues: ["HGB", "CREA", "CRP", "WBC"],
      qualityFlags: [],
      userCorrected: false,
    },
    {
      id: "col-020",
      sourceFileId: "src-002",
      columnName: "Station",
      inferredType: "string",
      semanticLabel: "Ward",
      domain: "lab_results",
      confidence: 0.76,
      sampleValues: ["A1", "B2", "C1", "A2"],
      qualityFlags: ["low_cardinality"],
      userCorrected: false,
    },
  ],
};
